// <auto-generated />
using Kol2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kol2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kol2.Models.Object", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Height")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int>("ObjectTypeId")
                        .HasColumnType("int");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Width")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.HasIndex("ObjectTypeId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Objects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 2.2m,
                            ObjectTypeId = 1,
                            WarehouseId = 1,
                            Width = 1.5m
                        },
                        new
                        {
                            Id = 2,
                            Height = 2.4m,
                            ObjectTypeId = 2,
                            WarehouseId = 1,
                            Width = 3.5m
                        },
                        new
                        {
                            Id = 3,
                            Height = 4.6m,
                            ObjectTypeId = 1,
                            WarehouseId = 2,
                            Width = 44.0m
                        });
                });

            modelBuilder.Entity("Kol2.Models.ObjectOwner", b =>
                {
                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("ObjectId", "OwnerId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Object_Owner");

                    b.HasData(
                        new
                        {
                            ObjectId = 1,
                            OwnerId = 1
                        },
                        new
                        {
                            ObjectId = 2,
                            OwnerId = 1
                        },
                        new
                        {
                            ObjectId = 3,
                            OwnerId = 1
                        });
                });

            modelBuilder.Entity("Kol2.Models.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ObjectType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "exampleType"
                        },
                        new
                        {
                            Id = 2,
                            Name = "anotherExampleType"
                        });
                });

            modelBuilder.Entity("Kol2.Models.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Jan",
                            LastName = "Kowalski",
                            PhoneNumber = "123456789"
                        });
                });

            modelBuilder.Entity("Kol2.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "bw1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "bw2"
                        });
                });

            modelBuilder.Entity("Kol2.Models.Object", b =>
                {
                    b.HasOne("Kol2.Models.ObjectType", "ObjectType")
                        .WithMany("Objects")
                        .HasForeignKey("ObjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kol2.Models.Warehouse", "Warehouse")
                        .WithMany("Objects")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectType");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Kol2.Models.ObjectOwner", b =>
                {
                    b.HasOne("Kol2.Models.Object", "Object")
                        .WithMany("ObjectOwners")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kol2.Models.Owner", "Owner")
                        .WithMany("ObjectOwners")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Object");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Kol2.Models.Object", b =>
                {
                    b.Navigation("ObjectOwners");
                });

            modelBuilder.Entity("Kol2.Models.ObjectType", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("Kol2.Models.Owner", b =>
                {
                    b.Navigation("ObjectOwners");
                });

            modelBuilder.Entity("Kol2.Models.Warehouse", b =>
                {
                    b.Navigation("Objects");
                });
#pragma warning restore 612, 618
        }
    }
}
